AWSTemplateFormatVersion: 2010-09-09

Description: An EKS cluster with spot ASG workers

Parameters:
  AMI:
    Type: String
    Default: ami-06ade0abbd8eca425 # amazon-eks-node-1.11-v20190109
  InstanceType:
    Type: String
    Default: t3.medium
  ClusterName:
    Type: String
    Default: SimpleEks
  IncomingCidr:
    Type: String
    Description: External IP range allowed to connect
    Default: 127.0.0.1/32

Resources:
  EKS:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      RoleArn: !GetAtt ClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
        - !Ref WorkerSG
        SubnetIds:
        - !ImportValue PrivateSubnetA
        - !ImportValue PrivateSubnetB
  
  ClusterRole:
    Description: Allows EKS to manage clusters on your behalf.
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
            Effect: Allow
            Principal:
              Service:
              - eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: 
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  WorkerSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: K8s-Worker-SG
      GroupDescription: Allow connections to kubernetes worker nodes
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 127.0.0.1/32 # Overwrite default egress rule
      Tags:
      - Key: Name
        Value: K8s Worker SG
      VpcId: !ImportValue SimpleVpc

  WorkerIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref WorkerSG
      IpProtocol: -1
      SourceSecurityGroupId: !Ref WorkerSG

  WorkerProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      - !Ref WorkerRole
      InstanceProfileName: WorkerProfile
  WorkerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: WorkerTemplate
      LaunchTemplateData:
        ImageId: !Ref AMI
        InstanceType: !Ref InstanceType
        IamInstanceProfile:
          Name: WorkerProfile
        SecurityGroupIds:
        - !Ref WorkerSG
        - !ImportValue OutgoingSG
        UserData:
          Fn::Base64:
            !Sub |
              #!/bin/bash
              set -o xtrace
              yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
              systemctl enable amazon-ssm-agent
              systemctl start amazon-ssm-agent

              /etc/eks/bootstrap.sh ${ClusterName} --kubelet-extra-args --node-labels=lifecycle=Ec2Spot

  WorkerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: LaunchTemplate
    Properties:
      MinSize: 2
      MaxSize: 2
      DesiredCapacity: 2
      MixedInstancesPolicy:
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: !Ref LaunchTemplate
            Version: !GetAtt [LaunchTemplate, LatestVersionNumber]
          Overrides:
          - InstanceType: t2.medium
          - InstanceType: t3.medium
        InstancesDistribution:
          OnDemandPercentageAboveBaseCapacity: 0 # i.e. 100% spot
          SpotAllocationStrategy: lowest-price
      VPCZoneIdentifier:
      - !ImportValue PrivateSubnetA
      - !ImportValue PrivateSubnetB
